services:
  ktor:
    build:
      context: ./ktor
      dockerfile: dockerfile
    ports:
      - '8080:8080'
    networks:
      - testnet
    restart: unless-stopped

  kotlin:
    build:
      context: ./kotlin
      dockerfile: dockerfile
    ports:
      - '8888:8888'
    networks:
      - testnet

networks:
  testnet:
    driver: bridge