FROM gradle:8.7.0

RUN echo "Creating working dir and copying files"
RUN mkdir /app
WORKDIR /app
COPY . .

RUN apt-get update
RUN apt-get autoremove -y 
RUN apt-get autoclean -y

RUN ./gradlew installDist

CMD ["./build/install/ktorexample/bin/ktorexample"]