FROM gradle

RUN echo "Creating working dir and copying files"
RUN mkdir /app
WORKDIR /app
COPY . .

RUN apt-get update
RUN apt-get autoremove -y 
RUN apt-get autoclean -y

RUN ./gradlew clean
RUN ./gradlew install

CMD ["./gradlew", "run"]